### ISSUE TITLE
Create meta-data structure to hold meta-data about datasets

### ISSUE THREAD

**Issue by stigbd** [stigbd/data-catalog#2]
Same way as openapi-files is related to catalog-info.yaml

First attempt may be inline.

Attributes must include:
- Title
- Description
- Owner
- Distribution (or something else that is not in Component.)
- Reference to API, if relevant

Format should be json.

**Comment by eidsvold** [comment]
Do we need a separate _openapi-like_ file to hold datasets' metadata? Could it be part of the `catalog-info` entity? E.g.
```YAML
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-dataset
  description: An example of a dataset
spec:
  type: dataset
  lifecycle: experimental
  owner: datascience
  system: parcelhub
  distribution: parquet
  providesApis: [example-rest-api]
```

It seems to me that we have to customize the [CatalogEntityPage](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogEntityPage/CatalogEntityPage.tsx) to display custom fields, if we don't create our own dataset plugin.
